name: main

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        dependency-versions: ['lowest', 'highest']
    name: PHP ${{ matrix.php-versions }} with ${{ matrix.dependency-versions }} versions of Composer dependencies
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpstan, php-cs-fixer:3
        coverage: pcov

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: "ramsey/composer-install@v2"
      with:
        dependency-versions: ${{ matrix.dependency-versions }}
      env:
        COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.COMPOSER_AUTH }}"}}'

    - name: Run PHP CS Fixer
      run: php-cs-fixer fix --diff --dry-run

    - name: Run PHPStan
      run: phpstan analyse src
